//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace ASE_Project.loginwebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="login1Soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class login1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback user_login_checkOperationCompleted;
        
        private System.Threading.SendOrPostCallback user_regOperationCompleted;
        
        private System.Threading.SendOrPostCallback vendor_regOperationCompleted;
        
        private System.Threading.SendOrPostCallback user_retrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback vendor_retrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback vendor_tryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public login1() {
            this.Url = global::ASE_Project.Properties.Settings.Default.ASE_Project_loginwebservice_login1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event user_login_checkCompletedEventHandler user_login_checkCompleted;
        
        /// <remarks/>
        public event user_regCompletedEventHandler user_regCompleted;
        
        /// <remarks/>
        public event vendor_regCompletedEventHandler vendor_regCompleted;
        
        /// <remarks/>
        public event user_retrieveCompletedEventHandler user_retrieveCompleted;
        
        /// <remarks/>
        public event vendor_retrieveCompletedEventHandler vendor_retrieveCompleted;
        
        /// <remarks/>
        public event vendor_tryCompletedEventHandler vendor_tryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/user_login_check", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int user_login_check(string name, string password, int type) {
            object[] results = this.Invoke("user_login_check", new object[] {
                        name,
                        password,
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void user_login_checkAsync(string name, string password, int type) {
            this.user_login_checkAsync(name, password, type, null);
        }
        
        /// <remarks/>
        public void user_login_checkAsync(string name, string password, int type, object userState) {
            if ((this.user_login_checkOperationCompleted == null)) {
                this.user_login_checkOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuser_login_checkOperationCompleted);
            }
            this.InvokeAsync("user_login_check", new object[] {
                        name,
                        password,
                        type}, this.user_login_checkOperationCompleted, userState);
        }
        
        private void Onuser_login_checkOperationCompleted(object arg) {
            if ((this.user_login_checkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.user_login_checkCompleted(this, new user_login_checkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/user_reg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int user_reg(string name, string email, string password, string contact_no, string zipcode) {
            object[] results = this.Invoke("user_reg", new object[] {
                        name,
                        email,
                        password,
                        contact_no,
                        zipcode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void user_regAsync(string name, string email, string password, string contact_no, string zipcode) {
            this.user_regAsync(name, email, password, contact_no, zipcode, null);
        }
        
        /// <remarks/>
        public void user_regAsync(string name, string email, string password, string contact_no, string zipcode, object userState) {
            if ((this.user_regOperationCompleted == null)) {
                this.user_regOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuser_regOperationCompleted);
            }
            this.InvokeAsync("user_reg", new object[] {
                        name,
                        email,
                        password,
                        contact_no,
                        zipcode}, this.user_regOperationCompleted, userState);
        }
        
        private void Onuser_regOperationCompleted(object arg) {
            if ((this.user_regCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.user_regCompleted(this, new user_regCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vendor_reg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int vendor_reg(string name, string email, string password, string contact_no, string zipcode, string street, string city, string time, string cat1) {
            object[] results = this.Invoke("vendor_reg", new object[] {
                        name,
                        email,
                        password,
                        contact_no,
                        zipcode,
                        street,
                        city,
                        time,
                        cat1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void vendor_regAsync(string name, string email, string password, string contact_no, string zipcode, string street, string city, string time, string cat1) {
            this.vendor_regAsync(name, email, password, contact_no, zipcode, street, city, time, cat1, null);
        }
        
        /// <remarks/>
        public void vendor_regAsync(string name, string email, string password, string contact_no, string zipcode, string street, string city, string time, string cat1, object userState) {
            if ((this.vendor_regOperationCompleted == null)) {
                this.vendor_regOperationCompleted = new System.Threading.SendOrPostCallback(this.Onvendor_regOperationCompleted);
            }
            this.InvokeAsync("vendor_reg", new object[] {
                        name,
                        email,
                        password,
                        contact_no,
                        zipcode,
                        street,
                        city,
                        time,
                        cat1}, this.vendor_regOperationCompleted, userState);
        }
        
        private void Onvendor_regOperationCompleted(object arg) {
            if ((this.vendor_regCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vendor_regCompleted(this, new vendor_regCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/user_retrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] user_retrieve(string name) {
            object[] results = this.Invoke("user_retrieve", new object[] {
                        name});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void user_retrieveAsync(string name) {
            this.user_retrieveAsync(name, null);
        }
        
        /// <remarks/>
        public void user_retrieveAsync(string name, object userState) {
            if ((this.user_retrieveOperationCompleted == null)) {
                this.user_retrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.Onuser_retrieveOperationCompleted);
            }
            this.InvokeAsync("user_retrieve", new object[] {
                        name}, this.user_retrieveOperationCompleted, userState);
        }
        
        private void Onuser_retrieveOperationCompleted(object arg) {
            if ((this.user_retrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.user_retrieveCompleted(this, new user_retrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vendor_retrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] vendor_retrieve(string name) {
            object[] results = this.Invoke("vendor_retrieve", new object[] {
                        name});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void vendor_retrieveAsync(string name) {
            this.vendor_retrieveAsync(name, null);
        }
        
        /// <remarks/>
        public void vendor_retrieveAsync(string name, object userState) {
            if ((this.vendor_retrieveOperationCompleted == null)) {
                this.vendor_retrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.Onvendor_retrieveOperationCompleted);
            }
            this.InvokeAsync("vendor_retrieve", new object[] {
                        name}, this.vendor_retrieveOperationCompleted, userState);
        }
        
        private void Onvendor_retrieveOperationCompleted(object arg) {
            if ((this.vendor_retrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vendor_retrieveCompleted(this, new vendor_retrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vendor_try", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] vendor_try(string user_id) {
            object[] results = this.Invoke("vendor_try", new object[] {
                        user_id});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void vendor_tryAsync(string user_id) {
            this.vendor_tryAsync(user_id, null);
        }
        
        /// <remarks/>
        public void vendor_tryAsync(string user_id, object userState) {
            if ((this.vendor_tryOperationCompleted == null)) {
                this.vendor_tryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onvendor_tryOperationCompleted);
            }
            this.InvokeAsync("vendor_try", new object[] {
                        user_id}, this.vendor_tryOperationCompleted, userState);
        }
        
        private void Onvendor_tryOperationCompleted(object arg) {
            if ((this.vendor_tryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vendor_tryCompleted(this, new vendor_tryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void user_login_checkCompletedEventHandler(object sender, user_login_checkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class user_login_checkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal user_login_checkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void user_regCompletedEventHandler(object sender, user_regCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class user_regCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal user_regCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vendor_regCompletedEventHandler(object sender, vendor_regCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vendor_regCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vendor_regCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void user_retrieveCompletedEventHandler(object sender, user_retrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class user_retrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal user_retrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vendor_retrieveCompletedEventHandler(object sender, vendor_retrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vendor_retrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vendor_retrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vendor_tryCompletedEventHandler(object sender, vendor_tryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vendor_tryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vendor_tryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591