//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace ASE_Project.vendormenus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="vendor_menusSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class vendor_menus : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback menu_retrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback item_addOperationCompleted;
        
        private System.Threading.SendOrPostCallback vendor_serviceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public vendor_menus() {
            this.Url = global::ASE_Project.Properties.Settings.Default.ASE_Project_vendormenus_vendor_menus;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event menu_retrieveCompletedEventHandler menu_retrieveCompleted;
        
        /// <remarks/>
        public event item_addCompletedEventHandler item_addCompleted;
        
        /// <remarks/>
        public event vendor_serviceCompletedEventHandler vendor_serviceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/menu_retrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] menu_retrieve(string vendorName) {
            object[] results = this.Invoke("menu_retrieve", new object[] {
                        vendorName});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void menu_retrieveAsync(string vendorName) {
            this.menu_retrieveAsync(vendorName, null);
        }
        
        /// <remarks/>
        public void menu_retrieveAsync(string vendorName, object userState) {
            if ((this.menu_retrieveOperationCompleted == null)) {
                this.menu_retrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmenu_retrieveOperationCompleted);
            }
            this.InvokeAsync("menu_retrieve", new object[] {
                        vendorName}, this.menu_retrieveOperationCompleted, userState);
        }
        
        private void Onmenu_retrieveOperationCompleted(object arg) {
            if ((this.menu_retrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.menu_retrieveCompleted(this, new menu_retrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/item_add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int item_add(string item_name, string item_price, string item_type, string item_desc, string main_vname) {
            object[] results = this.Invoke("item_add", new object[] {
                        item_name,
                        item_price,
                        item_type,
                        item_desc,
                        main_vname});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void item_addAsync(string item_name, string item_price, string item_type, string item_desc, string main_vname) {
            this.item_addAsync(item_name, item_price, item_type, item_desc, main_vname, null);
        }
        
        /// <remarks/>
        public void item_addAsync(string item_name, string item_price, string item_type, string item_desc, string main_vname, object userState) {
            if ((this.item_addOperationCompleted == null)) {
                this.item_addOperationCompleted = new System.Threading.SendOrPostCallback(this.Onitem_addOperationCompleted);
            }
            this.InvokeAsync("item_add", new object[] {
                        item_name,
                        item_price,
                        item_type,
                        item_desc,
                        main_vname}, this.item_addOperationCompleted, userState);
        }
        
        private void Onitem_addOperationCompleted(object arg) {
            if ((this.item_addCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.item_addCompleted(this, new item_addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vendor_service", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] vendor_service(string service) {
            object[] results = this.Invoke("vendor_service", new object[] {
                        service});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void vendor_serviceAsync(string service) {
            this.vendor_serviceAsync(service, null);
        }
        
        /// <remarks/>
        public void vendor_serviceAsync(string service, object userState) {
            if ((this.vendor_serviceOperationCompleted == null)) {
                this.vendor_serviceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onvendor_serviceOperationCompleted);
            }
            this.InvokeAsync("vendor_service", new object[] {
                        service}, this.vendor_serviceOperationCompleted, userState);
        }
        
        private void Onvendor_serviceOperationCompleted(object arg) {
            if ((this.vendor_serviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vendor_serviceCompleted(this, new vendor_serviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void menu_retrieveCompletedEventHandler(object sender, menu_retrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class menu_retrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal menu_retrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void item_addCompletedEventHandler(object sender, item_addCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class item_addCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal item_addCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vendor_serviceCompletedEventHandler(object sender, vendor_serviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vendor_serviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vendor_serviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591